### ISSUE TITLE
End-of-central-directory signature not found error when unzipping

### ISSUE THREAD

**Issue by maurobender** [julik/zip_kit#16]
Generating the zip file using this gem in a RoR 7.1 application results in a zip file that fails to unzip in certain scenarios:
- ✅ MacOS default desktop utility unzips the file without any issue.
- ❌ MacOS terminal [unzip](https://formulae.brew.sh/formula/unzip) utility fails to unzip due to EOCD issue.
- ❌ Widows default desktop utility fails to unzip due to invalid zip file.

These are some of the errors I'm seeing:
- __Windows__
<img width="488" alt="Captura de pantalla 2024-11-06 a la(s) 11 58 21" src="https://github.com/user-attachments/assets/226a5aab-7063-45d9-b6ed-0409bbd7f714">

- __MacOS unzip terminal utility__
```sh
$ unzip zip\ download\ tests.zip
Archive:  zip download tests.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of zip download tests.zip or
        zip download tests.zip.zip, and cannot find zip download tests.zip.ZIP, period.
```

```sh
$ zip -v zip\ download\ tests.zip
	zip warning: missing end signature--probably not a zip file (did you
	zip warning: remember to use binary mode when you transferred it?)
	zip warning: (if you are trying to read a damaged archive try -F)

zip error: Zip file structure invalid (zip download tests.zip)
```

```sh
$ zip -F zip\ download\ tests.zip --out fixed_zip.zip
Fix archive (-F) - assume mostly intact archive
	zip warning: bad archive - missing end signature
	zip warning: (If downloaded, was binary mode used?  If not, the
	zip warning:  archive may be scrambled and not recoverable)
	zip warning: Can't use -F to fix (try -FF)

zip error: Zip file structure invalid (zip download tests.zip)
```

Using `-FF` option with `zip` seems to fix it:

```sh
$ zip -FF zip\ download\ tests.zip --out fixed_zip.zip && unzip fixed_zip.zip
Fix archive (-FF) - salvage what can
	zip warning: Missing end (EOCDR) signature - either this archive
                     is not readable or the end is damaged
Is this a single-disk archive?  (y/n): y
  Assuming single-disk archive
Scanning for entries...
 copying: PSD Format.psd  (77821486 bytes)
 copying: TIFF Format.tiff  (53747976 bytes)
 copying: CR2 Format.cr2  (67127952 bytes)
Central Directory found...
Archive:  fixed_zip.zip
 extracting: PSD Format.psd
 extracting: TIFF Format.tiff
 extracting: CR2 Format.cr2
```

These are the versions I'm using:
- Ruby: 3.3.0
- Rails: 7.1
- zip_tricks: 5.6.0

Here is an example of the code I'm using to generate the file:
```rb
class Model
  has_one_attached :file
end

class DownloadsController
  def download_zip
    response.headers.reverse_merge!({
        'Content-Length' => content_size.to_s
    })

    zip_kit_stream(filename: 'zip download tests.zip') do |zip|
      add_files_to_zip(zip:)
    end
  end

  private

  def content_size
    ZipKit::SizeEstimator.estimate do |zip|
      models.each do |model|
        zip.add_stored_entry(
          filename: model.file.filename.to_s,
          size: model.file.blob.byte_size
        )
      end
    end
  end

  def add_files_to_zip(zip:)
    models.each do |model|
      # write_stored_file writes the file to the zip stream without compression
      zip.write_stored_file(model.file.filename.to_s) do |writer_for_file|
        model.file.blob.download { |chunk| writer_for_file << chunk }
      end
    end
  end

  def models
    @models ||= Model.all
  end
end
```

[Here is the zip file generated by my application](https://drive.google.com/file/d/1OgTPTrJJs4uswB-M2qnkrMt4XA1t2_pO/view?usp=sharing)

Is there something I'm doing wrong when I'm generating the zip file? Is there any tools I can use too understand better how to fix it?

Thanks!

**Comment by maurobender** [comment]
Expanding on this, I made some tests and find that commenting these lines:

```rb
response.headers.reverse_merge!({
   'Content-Length' => content_size.to_s
})
```

produces a valid zip file.

Looking further into the zip files I can see (using `tail -n 5 zip\ download\ tests.zip`) that the file streamed including the  'Content-Length' header was not containing the final comment in the file: `Written using ZipKit 6.3.1`. My guess here is that the `ZipKit::SizeEstimator.estimate` is returning only the size of the files without including the size of the End-of-central-directory signature and the comment, resulting in a truncated zip file.

Is there any way to know beforehand the size of the EoCD signature so I can add it to the pre-calculated size that will be use in the 'Content-Length' header?

Thanks!

**Comment by maurobender** [comment]
I end up solving it using the property `use_data_descriptor: true` when adding a stored file to the `ZipKit::SizeEstimator.estimate` but I don't really understand what changes doing that. Maybe it will be good to add some information about this to the docs.

**Comment by julik** [comment]
Hey @maurobender  apologies for hopping on this so late, but I believe I know what happens there.

I believe you can reproduce your issue by doing the following in the Rails console:

```ruby
estimated_size = ZipKit::SizeEstimator.estimate do |zip|
  models.each do |model|
    zip.add_stored_entry(
      filename: model.file.filename.to_s,
      size: model.file.blob.byte_size
    )
  end
end

blackhole_io = ZipKit::WriteAndTell.new(ZipKit::NullWriter)

ZipKit::Streamer.open(blackhole_io) do |zip|
  models.each do |model|
    # write_stored_file writes the file to the zip stream without compression
    zip.write_stored_file(model.file.filename.to_s) do |writer_for_file|
      model.file.blob.download { |chunk| writer_for_file << chunk }
    end
  end
end

warn [blackhole_io.pos, estimated_size].inspect
```

What you will likely notice is that your sizes are not equal. This happens because when using `write_stored_file` there is going to be a data descriptor after every file in the ZIP, it comes right after the file "body". This data descriptor is either 12 (4x3) or 20 (4 + 8 + 8) bytes in size. With every file that you add to the ZIP, there is going to be another data descriptor written, which will make the actual size of your output differ more and more from the estimated size.

When you place your incorrect size in `Content-Length` you are telling both your downstream web server _and_ the receiving client that you are about to send it N bytes. You then proceed to send it N+(size of your data descriptors) bytes. The web server is free to not even accept that data, because you are giving it more data than you "promised". Same for the browser.

As the end result, your EOCD record - which is at the very end of the ZIP - ends up getting discarded. Either the webserver does not send it onwards (since it lies past the maximum response body size you declared with the `Content-Length` header), or Rails is not sending it to the webserver, or the browser discards those bytes at the end.

What happens afterwards differs per unzipping application, indeed. The default (and correct!) way to read a ZIP is to first look for that EOCD record - which is lost, in this case. Then from the EOCD record the unarchiver will look for the central directory entries, and read those. It can then random-access offsets in the ZIP where the file bodies are. But if there is no central directory (or no EOCD record which says where entries end and the central directory starts!) the unarchiver _may_ support a reversion where it will go and read the ZIP from the start (offset 0), and attempt to extract files one by one. This has other issues - for example, data descriptors do not support proper "nesting" unless the unarchiver scans for them, which is a perfect vehicle for ZIP bombs and the like. That's why "straight ahead reading" usually is a "secondary", "reversion" mode for unarchiving apps.

So what you did is correct - when you estimate the size of the output you need to tell the `SizeEstimator` that you intend to be using data descriptors. Then the computed size will be "padded" to account for the bytesize of those descriptors exactly, and the two sizes will match.


I will think about adding the tidbit to the docs for the `SizeEstimator` - but, in all honesty, it seems you are one of the very few people on Earth who ended up actually using it 😄  for which I salute you 🍾

**Comment by maurobender** [comment]
Hey @julik! First of all, thank you so much for all the hard work you’ve put into this gem and for providing such a clear explanation of what was happening. I believe adding this to the documentation would be really helpful for anyone with a similar use case. Maybe a simple mention of the issue along with a link to your response could be great! If you’d like, I'm happy to contribute by making the change myself and submitting a PR for you to review. Let me know what you think!

**Comment by julik** [comment]
I've added more comments to the estimator - what can I do more? Should the examples include this use case too? What were you relying on mostly - the examples or the YARD API documentation?
