### ISSUE TITLE
Unsized Rack output using HTTP/2

### ISSUE THREAD

**Issue by julik** [julik/zip_kit#2]
Here https://github.com/julik/zip_kit/blob/main/lib/zip_kit/output_enumerator.rb#L130 there is a branch where we regress to a cached Tempfile if the downstream proxy is HTTP/1.0 (because chunked transfer encoding is not supported there). But I wonder - with a server like Falcon with native HTTP/2 - what would the value of the header be? And given the fact there is no chunked encoding in HTTP/2, can we "just" return the `OutputEnumerator` "bare" to the Rack server and omit the `Content-Length`?

@ioquatix would love to hear your thoughts on this (Falcon is the only "true" Rack HTTP/2 server atm, right?)

**Comment by ioquatix** [comment]
As far as I know, there is no other native Ruby HTTP/2 server.

Wrapping the body is handled here: https://github.com/socketry/protocol-rack/blob/ec318a60b894553633a43e62d78de07153274cdd/lib/protocol/rack/body.rb#L15

In general, `falcon` will not forward user-provided [`content-length`](https://github.com/socketry/protocol-rack/blob/ec318a60b894553633a43e62d78de07153274cdd/lib/protocol/rack/body.rb#L18-L19) and [`transfer-encoding`](https://github.com/socketry/protocol-rack/blob/ec318a60b894553633a43e62d78de07153274cdd/lib/protocol/rack/response.rb#L28-L43). Falcon considers these headers to be part of the protocol layer - as in - if you get it wrong, bad things happen. With regard to `content-length` - we don't trust the user to compute it correctly - IIRC, we sometimes use it as a hint. `transfer-encoding` is only relevant to HTTP/1.1 - i.e. invalid for HTTP/1.0 and HTTP/2+.

HTTP/1.0 does not imply streaming is not supported, but it does force the use of `connection: close`. That is because as you correctly point out, chunked encoding is not supported - and if you don't know the length ahead of time, the only other option for HTTP/1.0 is to say "I don't know the content length, so I'm going to stream the data to you and close the connection when I'm done.". There is one other caveat to this approach - if the response is interrupted prematurely, the client won't be able to tell the difference between a complete or partial transmission - except that of course the response body (ZIP archive) might be corrupt.

With respect to your main question about how to construct the response: for performance reasons, it's best to leave this up to the server. Falcon will deal with all the above scenarios in the most efficient way possible and we continue to optimise various response patterns according to the protocol and what information we have at the time, including HTTP/1.0 when the content length is not known.

Therefore, I would advise you not to do extra work to compute `content-length` as the server may ignore it. You should also avoid adding `transfer-encoding` headers as they will be ignored. You should follow the rack specification for response body:

- An array of String instances (content-length can be computed).
- Something that responds to `#each` (content-length can't be computed).

I would recommend you remove the `transfer-encoding` header and consider whether `content-length` is expensive to compute - if not - you can add it, but it may be ignored (e.g. HTTP/1.1+ doesn't need it).

**Comment by julik** [comment]
It is expensive to compute in this case, and I rather not precompute it. However, using explicit `chunked` encoding with HTTP/1.1 will be the correct step (IMO) for most situations - it provides an explicit content encoding and does not leave the server too much room for creativity, so I rather keep it that way. It is also needed so that `Rack::ContentLength` does not attempt to compute the content length upfront. Does Falcon set `HTTP_VERSION` in the Rack env? because it looks like for Falcon we indeed can "just return an `each`'able and let the server deal with it".

**Comment by ioquatix** [comment]
`Rack::ContentLength` is a mistake and we should deprecate and remove it.

Are you saying that `Puma` won't use chunked encoding unless you explicitly specify `transfer-encoding`? Can you explain the case where that's practically useful?

**Comment by julik** [comment]
> `Rack::ContentLength` is a mistake and we should deprecate and remove it.

I agree, but this gem is trying to provide a Rack response body which is of unknown size, should be iterable _and_ compatible with the widest range of webservers. And (ideally) it should be able to bypass `Rack::ContentLength` if said middleware is downstream in the stack. I believe Puma will do chunking by itself if really asked to, but I do remember there were bugs mentioned someplace where this wasn't handled correctly. Since this gem should work for people on the widest range of servers (and their versions too) I do want to provide some "solidifying" workarounds for this. Last I examined the code "just preceding" `fast_write` in Puma it was different between the 5.x and the 6.x branches 🤔 

This is why for the "most common case" (http 1.1 supported) I believe doing the chunking "earlier" in the pipe is the safest approach. This is also what Rails does in its `Live` module.

As to `Content-Length` - fair enough, but I did - for one - write a module that provides range-addressable responses, and it really should have `Content-Length` if you want to be compatible with non-HTTP2 webservers (which are a majority).

I guess what I am saying is "what is the correct combo of "content-length or no content-length and iterable Rack body" for a non-presized response with HTTP/2, and does Falcon tell me that it is running with HTTP/2 via a header in `env`?

**Comment by ioquatix** [comment]
@nateberkopec - does Puma use chunked encoding for enumerable bodies when the response is HTTP/1.1? Or does it depend on `transfer-encoding` being set by the app?

**Comment by julik** [comment]
FWIW when I reviewed the last Puma version it did apply chunked encoding automatically. But I would need to go scanning in the repo whether there were any bugs with this previously.

**Comment by ioquatix** [comment]
I personally think it's best if you follow the guidelines for Rack 3 and avoid trying to craft responses for specific server implementations.

**Comment by julik** [comment]
Again - I'd love to, but I want this thing to work on a widest range of Rack versions because this is an infrastructure gem, not an embeddable app. I would want to be able to provide compat for Rails 5 -> Rails 7+ throughout, and Rack 1 -> Rack 3 throughout, with all webservers. Insofar as possible. Also I've seen plenty of reports from people having their responses "suddenly start buffering". Granted - last time that was due to `Rack::ETag`, but I also vaguely remember there being issues with `Rack::ContentLength`... which Rails versions include it by default? I don't remember. Which Rackup versions add `ContentLength` to the default `Builder`? I don't remember either 🤔  So while following the latest spec correctly is probably the easiest - it might not be enough in this particular case.

Do I understand correctly that your baseline recommendation is "no Content-Length, and an unsized `each`-able body without chunked transfer encoding, for all HTTP versions"? and servers should "just" do the right thing?

**Comment by ioquatix** [comment]
> Do I understand correctly that your baseline recommendation is "no Content-Length, and an unsized each-able body without chunked transfer encoding, for all HTTP versions"? and servers should "just" do the right thing?

Yes, that's correct, and it should also work on all old versions of Rack.

**Comment by julik** [comment]
@ioquatix thank you for your input ❤️
